using System.ComponentModel;

namespace LabExtended.Core.Configs.Sections
{
    public class LoopSection
    {
        [Description("Whether or not to modify Player loops (adding a custom one and removing ones specified in the config below).")]
        public bool ModifyLoops { get; set; } = false;

        [Description("A list of player loops that will NOT be removed.")]
        public List<string> RequiredLoops { get; set; } = new List<string>()
        {
            "UnityEngine.PlayerLoop.PostLateUpdate+GraphicsWarmupPreloadedShaders",
            "UnityEngine.PlayerLoop.PostLateUpdate+ProfilerEndFrame",
            "UnityEngine.PlayerLoop.PostLateUpdate+XRPreEndFrame",
            "UnityEngine.PlayerLoop.PostLateUpdate+ExecuteGameCenterCallbacks",
            "UnityEngine.PlayerLoop.PostLateUpdate+MemoryFrameMaintenance",
            "UnityEngine.PlayerLoop.PostLateUpdate+ProfilerSynchronizeStats",
            "UnityEngine.PlayerLoop.PostLateUpdate+ThreadedLoadingDebug",
            "UnityEngine.PlayerLoop.PostLateUpdate+ResetInputAxis",
            "UnityEngine.PlayerLoop.PostLateUpdate+ShaderHandleErrors",
            "UnityEngine.PlayerLoop.PostLateUpdate+GUIClearEvents",
            "UnityEngine.PlayerLoop.PostLateUpdate+TriggerEndOfFrameCallbacks",
            "UnityEngine.PlayerLoop.PostLateUpdate+InputEndFrame",
            "UnityEngine.PlayerLoop.PostLateUpdate+UpdateResolution",
            "UnityEngine.PlayerLoop.PostLateUpdate+PlayerSendFramePostPresent",
            "UnityEngine.PlayerLoop.PostLateUpdate+ClearImmediateRenderers",
            "UnityEngine.PlayerLoop.PostLateUpdate+PresentAfterDraw",
            "UnityEngine.PlayerLoop.PostLateUpdate+UpdateCaptureScreenshot",
            "UnityEngine.PlayerLoop.PostLateUpdate+PlayerSendFrameComplete",
            "UnityEngine.PlayerLoop.PostLateUpdate+BatchModeUpdate",
            "UnityEngine.PlayerLoop.PostLateUpdate+FinishFrameRendering",
            "UnityEngine.PlayerLoop.PostLateUpdate+PhysicsSkinnedClothFinishUpdate",
            "UnityEngine.PlayerLoop.PostLateUpdate+PlayerEmitCanvasGeometry",
            "UnityEngine.PlayerLoop.PostLateUpdate+DirectorRenderImage",
            "UnityEngine.PlayerLoop.PostLateUpdate+UpdateVideo",
            "UnityEngine.PlayerLoop.PostLateUpdate+SortingGroupsUpdate",
            "UnityEngine.PlayerLoop.PostLateUpdate+ProcessWebSendMessages",
            "UnityEngine.PlayerLoop.PostLateUpdate+UpdateAllSkinnedMeshes",
            "UnityEngine.PlayerLoop.PostLateUpdate+EnlightenRuntimeUpdate",
            "UnityEngine.PlayerLoop.PostLateUpdate+UpdateLightProbeProxyVolumes",
            "UnityEngine.PlayerLoop.PostLateUpdate+UpdateAllRenderers",
            "UnityEngine.PlayerLoop.PostLateUpdate+XRPostLateUpdate",
            "UnityEngine.PlayerLoop.PostLateUpdate+UpdateCustomRenderTextures",
            "UnityEngine.PlayerLoop.PostLateUpdate+EndGraphicsJobsAfterScriptLateUpdate",
            "UnityEngine.PlayerLoop.PostLateUpdate+ParticleSystemEndUpdateAll",
            "UnityEngine.PlayerLoop.PostLateUpdate+VFXUpdate",
            "UnityEngine.PlayerLoop.PostLateUpdate+UpdateAudio",
            "UnityEngine.PlayerLoop.PostLateUpdate+PlayerUpdateCanvases",
            "UnityEngine.PlayerLoop.PostLateUpdate+UpdateRectTransform",
            "UnityEngine.PlayerLoop.PostLateUpdate+PhysicsSkinnedClothBeginUpdate",
            "UnityEngine.PlayerLoop.PostLateUpdate+ScriptRunDelayedDynamicFrameRate",
            "UnityEngine.PlayerLoop.PostLateUpdate+DirectorLateUpdate",
            "UnityEngine.PlayerLoop.PostLateUpdate+PlayerSendFrameStarted",

            "Mirror.NetworkLoop",

            "UnityEngine.PlayerLoop.PreLateUpdate+ScriptRunBehaviourLateUpdate",
            "UnityEngine.PlayerLoop.PreLateUpdate+Physics2DLateUpdate",
            "UnityEngine.PlayerLoop.PreLateUpdate+ParticleSystemBeginUpdateAll",
            "UnityEngine.PlayerLoop.PreLateUpdate+ConstraintManagerUpdate",
            "UnityEngine.PlayerLoop.PreLateUpdate+EndGraphicsJobsAfterScriptUpdate",
            "UnityEngine.PlayerLoop.PreLateUpdate+UIElementsUpdatePanels",
            "UnityEngine.PlayerLoop.PreLateUpdate+DirectorDeferredEvaluate",
            "UnityEngine.PlayerLoop.PreLateUpdate+DirectorUpdateAnimationEnd",
            "UnityEngine.PlayerLoop.PreLateUpdate+LegacyAnimationUpdate",
            "UnityEngine.PlayerLoop.PreLateUpdate+DirectorUpdateAnimationBegin",
            "UnityEngine.PlayerLoop.PreLateUpdate+AIUpdatePostScript",

            "UnityEngine.PlayerLoop.Update+DirectorUpdate",
            "UnityEngine.PlayerLoop.Update+ScriptRunDelayedTasks",
            "UnityEngine.PlayerLoop.Update+ScriptRunDelayedDynamicFrameRate",
            "UnityEngine.PlayerLoop.Update+ScriptRunBehaviourUpdate",

            "UnityEngine.PlayerLoop.PreUpdate+UpdateVideo",
            "UnityEngine.PlayerLoop.PreUpdate+WindUpdate",
            "UnityEngine.PlayerLoop.PreUpdate+AIUpdate",
            "UnityEngine.PlayerLoop.PreUpdate+SendMouseEvents",
            "UnityEngine.PlayerLoop.PreUpdate+NewInputUpdate",
            "UnityEngine.PlayerLoop.PreUpdate+IMGUISendQueuedEvents",
            "UnityEngine.PlayerLoop.PreUpdate+CheckTexFieldInput",
            "UnityEngine.PlayerLoop.PreUpdate+Physics2DUpdate",
            "UnityEngine.PlayerLoop.PreUpdate+PhysicsUpdate",

            "UnityEngine.PlayerLoop.FixedUpdate+ScriptRunDelayedFixedFrameRate",
            "UnityEngine.PlayerLoop.FixedUpdate+DirectorFixedUpdatePostPhysics",
            "UnityEngine.PlayerLoop.FixedUpdate+PhysicsClothFixedUpdate",
            "UnityEngine.PlayerLoop.FixedUpdate+Physics2DFixedUpdate",
            "UnityEngine.PlayerLoop.FixedUpdate+PhysicsFixedUpdate",
            "UnityEngine.PlayerLoop.FixedUpdate+XRFixedUpdate",
            "UnityEngine.PlayerLoop.FixedUpdate+LegacyFixedAnimationUpdate",
            "UnityEngine.PlayerLoop.FixedUpdate+DirectorFixedUpdate",
            "UnityEngine.PlayerLoop.FixedUpdate+ScriptRunBehaviourFixedUpdate",
            "UnityEngine.PlayerLoop.FixedUpdate+AudioFixedUpdate",
            "UnityEngine.PlayerLoop.FixedUpdate+DirectorFixedSampleTime",
            "UnityEngine.PlayerLoop.FixedUpdate+NewInputFixedUpdate",
            "UnityEngine.PlayerLoop.FixedUpdate+ClearLines",

            "UnityEngine.PlayerLoop.EarlyUpdate+PerformanceAnalyticsUpdate",
            "UnityEngine.PlayerLoop.EarlyUpdate+SpriteAtlasManagerUpdate",
            "UnityEngine.PlayerLoop.EarlyUpdate+PhysicsResetInterpolatedTransformPosition",
            "UnityEngine.PlayerLoop.EarlyUpdate+DispatchEventQueueEvents",
            "UnityEngine.PlayerLoop.EarlyUpdate+ARCoreUpdate",
            "UnityEngine.PlayerLoop.EarlyUpdate+DeliverIosPlatformEvents",
            "UnityEngine.PlayerLoop.EarlyUpdate+UpdateKinect",
            "UnityEngine.PlayerLoop.EarlyUpdate+ScriptRunDelayedStartupFrame",
            "UnityEngine.PlayerLoop.EarlyUpdate+ProcessRemoteInput",
            "UnityEngine.PlayerLoop.EarlyUpdate+UpdateInputManager",
            "UnityEngine.PlayerLoop.EarlyUpdate+XRUpdate",
            "UnityEngine.PlayerLoop.EarlyUpdate+UpdateCanvasRectTransform",
            "UnityEngine.PlayerLoop.EarlyUpdate+UpdateMainGameViewRect",
            "UnityEngine.PlayerLoop.EarlyUpdate+PlayerCleanupCachedData",
            "UnityEngine.PlayerLoop.EarlyUpdate+RendererNotifyInvisible",
            "UnityEngine.PlayerLoop.EarlyUpdate+UpdatePreloading",
            "UnityEngine.PlayerLoop.EarlyUpdate+UpdateTextureStreamingManager",
            "UnityEngine.PlayerLoop.EarlyUpdate+UpdateStreamingManager",
            "UnityEngine.PlayerLoop.EarlyUpdate+UpdateAsyncReadbackManager",
            "UnityEngine.PlayerLoop.EarlyUpdate+ResetFrameStatsAfterPresent",
            "UnityEngine.PlayerLoop.EarlyUpdate+PresentBeforeUpdate",
            "UnityEngine.PlayerLoop.EarlyUpdate+ClearLines",
            "UnityEngine.PlayerLoop.EarlyUpdate+ClearIntermediateRenderers",
            "UnityEngine.PlayerLoop.EarlyUpdate+ProcessMouseInWindow",
            "UnityEngine.PlayerLoop.EarlyUpdate+ExecuteMainThreadJobs",
            "UnityEngine.PlayerLoop.EarlyUpdate+UnityWebRequestUpdate",
            "UnityEngine.PlayerLoop.EarlyUpdate+AnalyticsCoreStatsUpdate",
            "UnityEngine.PlayerLoop.EarlyUpdate+GpuTimestamp",
            "UnityEngine.PlayerLoop.EarlyUpdate+PollPlayerConnection",

            "UnityEngine.PlayerLoop.Initialization+XREarlyUpdate",
            "UnityEngine.PlayerLoop.Initialization+SynchronizeState",
            "UnityEngine.PlayerLoop.Initialization+SynchronizeInputs",
            "UnityEngine.PlayerLoop.Initialization+AsyncUploadTimeSlicedUpdate",
            "UnityEngine.PlayerLoop.Initialization+DirectorSampleTime",
            "UnityEngine.PlayerLoop.Initialization+UpdateCameraMotionVectors",
            "UnityEngine.PlayerLoop.Initialization+ProfilerStartFrame",

            "UnityEngine.PlayerLoop.TimeUpdate+WaitForLastPresentationAndUpdateTime",

            "LabExtended.Utilities.Unity.PlayerLoopHelper+CustomAfterPlayerLoop",
            "LabExtended.Utilities.Unity.PlayerLoopHelper+CustomBeforePlayerLoop"
        };
    }
}
