using System.ComponentModel;

namespace LabExtended.Core.Configs.Sections
{
    public class LoopSection
    {
        [Description("Whether or not to modify Player loops (adding a custom one and removing ones specified in the config below).")]
        public bool ModifyLoops { get; set; } = true;

        [Description("A list of player loops that will be removed.")]
        public List<string> RemovedLoops { get; set; } = new()
        {
            "UnityEngine.PlayerLoop.PostLateUpdate+BatchModeUpdate",
            "UnityEngine.PlayerLoop.PostLateUpdate+InputEndFrame",
            "UnityEngine.PlayerLoop.PostLateUpdate+ShaderHandleErrors",
            "UnityEngine.PlayerLoop.PostLateUpdate+ObjectDispatcherPostLateUpdate",
            "UnityEngine.PlayerLoop.PostLateUpdate+GraphicsWarmupPreloadedShaders",
            "UnityEngine.PlayerLoop.PostLateUpdate+XRPreEndFrame",
            "UnityEngine.PlayerLoop.PostLateUpdate+ExecuteGameCenterCallbacks",
            "UnityEngine.PlayerLoop.PostLateUpdate+MemoryFrameMaintenance",
            "UnityEngine.PlayerLoop.PostLateUpdate+ThreadedLoadingDebug",
            "UnityEngine.PlayerLoop.PostLateUpdate+ResetInputAxis",
            "UnityEngine.PlayerLoop.PostLateUpdate+ShaderHandleError",
            "UnityEngine.PlayerLoop.PostLateUpdate+GUIClearEvents",
            "UnityEngine.PlayerLoop.PostLateUpdate+UpdateResolution",
            "UnityEngine.PlayerLoop.PostLateUpdate+ClearImmediateRenderers",
            "UnityEngine.PlayerLoop.PostLateUpdate+PresentAfterDraw",
            "UnityEngine.PlayerLoop.PostLateUpdate+UpdateCaptureScreenshot",
            "UnityEngine.PlayerLoop.PostLateUpdate+PhysicsSkinnedClothFinishUpdate",
            "UnityEngine.PlayerLoop.PostLateUpdate+UIElementsRenderBatchModeOffscreen",
            "UnityEngine.PlayerLoop.PostLateUpdate+PlayerEmitCanvasGeometry",
            "UnityEngine.PlayerLoop.PostLateUpdate+UpdateVideo",
            "UnityEngine.PlayerLoop.PostLateUpdate+UpdateVideoTextures",
            "UnityEngine.PlayerLoop.PostLateUpdate+SortingGroupsUpdate",
            "UnityEngine.PlayerLoop.PostLateUpdate+UpdateAllSkinnedMeshes",
            "UnityEngine.PlayerLoop.PostLateUpdate+EnlightenRuntimeUpdate",
            "UnityEngine.PlayerLoop.PostLateUpdate+UpdateLightProbeProxyVolumes",
            "UnityEngine.PlayerLoop.PostLateUpdate+UpdateAllRenderers",
            "UnityEngine.PlayerLoop.PostLateUpdate+XRPostLateUpdate",
            "UnityEngine.PlayerLoop.PostLateUpdate+UpdateCustomRenderTextures",
            "UnityEngine.PlayerLoop.PostLateUpdate+VFXUpdate",
            "UnityEngine.PlayerLoop.PostLateUpdate+UpdateAudio",
            "UnityEngine.PlayerLoop.PostLateUpdate+UIElementsRepaintPanels",
            "UnityEngine.PlayerLoop.PostLateUpdate+PlayerUpdateCanvases",
            "UnityEngine.PlayerLoop.PostLateUpdate+UpdateRectTransform",
            "UnityEngine.PlayerLoop.PostLateUpdate+PhysicsSkinnedClothBeginUpdate",
            "UnityEngine.PlayerLoop.PostLateUpdate+ParticleSystemEndUpdateAll",
            "UnityEngine.PlayerLoop.PostLateUpdate+ProfilerEndFrame",
            "UnityEngine.PlayerLoop.PostLateUpdate+ProfilerSynchronizeStats",
            "UnityEngine.PlayerLoop.PostLateUpdate+EndGraphicsJobsAfterScriptLateUpdate",
            "UnityEngine.Rendering.HighDefinition.LightLateUpdate",
            "UnityEngine.PlayerLoop.PreLateUpdate+ParticleSystemBeginUpdateAll",
            "UnityEngine.PlayerLoop.PreLateUpdate+Physics2DLateUpdate",
            "UnityEngine.PlayerLoop.PreLateUpdate+EndGraphicsJobsAfterScriptUpdate",
            "UnityEngine.PlayerLoop.PreLateUpdate+UIElementsUpdatePanels",
            "UnityEngine.PlayerLoop.PreLateUpdate+AccessibilityUpdate",
            "UnityEngine.PlayerLoop.PreLateUpdate+LegacyAnimationUpdate",
            "UnityEngine.PlayerLoop.PreLateUpdate+AIUpdatePostScript",
            "UnityEngine.PlayerLoop.PreLateUpdate+ConstraintManagerUpdate",
            "UnityEngine.Rendering.HighDefinition.LightLateUpdate",
            "UnityEngine.Rendering.HighDefinition.LocalVolumetricFogManager+RegisterLocalVolumetricFogEarlyUpdate",
            "UnityEngine.PlayerLoop.PreUpdate+UpdateVideo",
            "UnityEngine.PlayerLoop.PreUpdate+WindUpdate",
            "UnityEngine.PlayerLoop.PreUpdate+AIUpdate",
            "UnityEngine.PlayerLoop.PreUpdate+SendMouseEvents",
            "UnityEngine.PlayerLoop.PreUpdate+InputForUIUpdate",
            "UnityEngine.PlayerLoop.PreUpdate+NewInputUpdate",
            "UnityEngine.PlayerLoop.PreUpdate+IMGUISendQueuedEvents",
            "UnityEngine.PlayerLoop.PreUpdate+CheckTexFieldInput",
            "UnityEngine.PlayerLoop.PreUpdate+PhysicsClothUpdate",
            "UnityEngine.PlayerLoop.PreUpdate+Physics2DUpdate",
            "UnityEngine.PlayerLoop.FixedUpdate+PhysicsClothFixedUpdate",
            "UnityEngine.PlayerLoop.FixedUpdate+Physics2DFixedUpdate",
            "UnityEngine.PlayerLoop.FixedUpdate+XRFixedUpdate",
            "UnityEngine.PlayerLoop.FixedUpdate+LegacyFixedAnimationUpdate",
            "UnityEngine.PlayerLoop.FixedUpdate+NewInputFixedUpdate",
            "UnityEngine.PlayerLoop.FixedUpdate+ClearLines",
            "UnityEngine.PlayerLoop.FixedUpdate+AudioFixedUpdate",
            "UnityEngine.PlayerLoop.EarlyUpdate+PerformanceAnalyticsUpdate",
            "UnityEngine.PlayerLoop.EarlyUpdate+SpriteAtlasManagerUpdate",
            "UnityEngine.PlayerLoop.EarlyUpdate+Physics2DEarlyUpdate",
            "UnityEngine.PlayerLoop.EarlyUpdate+ARCoreUpdate",
            "UnityEngine.PlayerLoop.EarlyUpdate+DeliverIosPlatformEvents",
            "UnityEngine.PlayerLoop.EarlyUpdate+UpdateKinect",
            "UnityEngine.PlayerLoop.EarlyUpdate+ProcessRemoteInput",
            "UnityEngine.PlayerLoop.EarlyUpdate+UpdateInputManager",
            "UnityEngine.PlayerLoop.EarlyUpdate+XRUpdate",
            "UnityEngine.PlayerLoop.EarlyUpdate+UpdateCanvasRectTransform",
            "UnityEngine.PlayerLoop.EarlyUpdate+UpdateMainGameViewRect",
            "UnityEngine.PlayerLoop.EarlyUpdate+ProcessMouseInWindow",
            "UnityEngine.PlayerLoop.EarlyUpdate+AnalyticsCoreStatsUpdate",
            "UnityEngine.PlayerLoop.EarlyUpdate+GpuTimestamp",
            "UnityEngine.PlayerLoop.EarlyUpdate+PollPlayerConnection",
            "UnityEngine.PlayerLoop.EarlyUpdate+DispatchEventQueueEvents",
            "UnityEngine.PlayerLoop.EarlyUpdate+RendererNotifyInvisible",
            "UnityEngine.PlayerLoop.EarlyUpdate+ClearLines",
            "UnityEngine.PlayerLoop.EarlyUpdate+ClearIntermediateRenderers",
            "UnityEngine.PlayerLoop.EarlyUpdate+UpdateContentLoading",
            "UnityEngine.PlayerLoop.EarlyUpdate+UpdateTextureStreamingManager",
            "UnityEngine.PlayerLoop.EarlyUpdate+UpdateStreamingManager",
            "UnityEngine.PlayerLoop.EarlyUpdate+UpdateAsyncReadbackManager",
            "UnityEngine.PlayerLoop.EarlyUpdate+UpdateAsyncInstantiate",
            "UnityEngine.PlayerLoop.EarlyUpdate+ExecuteMainThreadJobs",
            "UnityEngine.PlayerLoop.Initialization+XREarlyUpdate",
            "UnityEngine.PlayerLoop.Initialization+SynchronizeState",
            "UnityEngine.PlayerLoop.Initialization+SynchronizeInputs",
            "UnityEngine.PlayerLoop.Initialization+UpdateCameraMotionVectors",
            "UnityEngine.PlayerLoop.Initialization+AsyncUploadTimeSlicedUpdate"
        };

        [Description("A list of all present loops.")]
        public List<string> AllLoops { get; set; } = new();
    }
}
