name: .NET
run-name: Test
on:
  push:
    branches: [ "actions" ]
  pull_request:
    branches: [ "actions" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      LAB_EX_REFERENCES: "dependencies"
      SL_REFERENCES: "dependencies"

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Download Dependencies
      run: wget https://cdn.peanutclub.eu/labextended/dependencies.rar
    - name: Extract dependencies
      run: rar x dependencies.rar
    - name: Build
      run: dotnet build --no-restore
    - name: Upload artifacts
      uses: actions/upload-artifact@v4.3.4
      with:
        name: labextended-dev
        path: artifacts
        overwrite: true
